######################################################################
# Automatically generated by qmake (2.00a) Tue Apr 11 13:04:58 2006
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += compat common schema kxml_compiler/kschema.pro kxml_compiler/tests kxforms kxforms/tests
