######################################################################
# Automatically generated by qmake (2.00a) Mon Apr 10 13:23:45 2006
######################################################################

TEMPLATE = lib
TARGET = kxmlcommon
DEPENDPATH += .
INCLUDEPATH += . .. ../compat

# Input
HEADERS += messagehandler.h nsmanager.h parsercontext.h qname.h
SOURCES += messagehandler.cpp \
           nsmanager.cpp \
           parsercontext.cpp \
           qname.cpp

CONFIG += staticlib
