######################################################################
# Automatically generated by qmake (2.00a) Mon Apr 10 13:57:52 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += . ..

# Input
HEADERS += 
SOURCES += schematest.cpp

MAKEFILE = Makefile.schematest

QT += xml

LIBS += -L../common -lkxmlcommon
LIBS += -L../schema -lschema
