// This file is generated by kxml_compiler from simple.xml.
// All changes you do to this file will be lost.
/*
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
    USA.
*/
#ifndef SIMPLE_H
#define SIMPLE_H

#include <QString>
#include <QDomElement>
#include <QList>

class Food
{
  public:
    typedef QList<Food> List;

  public:
    void setName( const QString &v );
    QString name() const;
    void setTaste( const QString &v );
    QString taste() const;
    /**
      Parse XML object from DOM element.
     */
    static Food parseElement( const QDomElement &element, bool *ok );
    QString writeElement();

  private:
    QString mName;
    QString mTaste;
};

class Simple
{
  public:
    void addFood( const Food &v );
    void setFoodList( const Food::List &v );
    Food::List foodList() const;
    /**
      Parse XML object from DOM element.
     */
    static Simple parseElement( const QDomElement &element, bool *ok );
    QString writeElement();
    static Simple parseFile( const QString &filename, bool *ok );
    bool writeFile( const QString &filename );

  private:
    Food::List mFoodList;
};

#endif
