######################################################################
# Automatically generated by qmake (2.01a) Mo Mrz 5 08:26:06 2007
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET +=
DEPENDPATH += .
INCLUDEPATH += . ../../common ../../compat ../.. ..

# Input
HEADERS += kxformstest.h \
           ../form.h \
           ../formcreator.h \
           ../formgui.h \
           ../guielement.h \
           ../guihandler.h \
           ../guihandlerdialogs.h \
           ../guihandlerflat.h \
           ../hints.h \
           ../input.h \
           ../kresult.h \
           ../list.h \
           ../listmodel.h \
           ../manager.h \
           ../reference.h \
           ../select1.h \
           ../textarea.h \
           ../xformscommon.h \
           ../xmlbuilder.h \
           ../prefs.h \
           ../section.h \
           ../dispatcher.h
SOURCES += kxformstest.cpp \
           ../form.cpp \
           ../formcreator.cpp \
           ../formgui.cpp \
           ../guielement.cpp \
           ../guihandler.cpp \
           ../guihandlerdialogs.cpp \
           ../guihandlerflat.cpp \
           ../hints.cpp \
           ../input.cpp \
           ../kresult.cpp \
           ../list.cpp \
           ../listmodel.cpp \
           ../manager.cpp \
           ../reference.cpp \
           ../select1.cpp \
           ../textarea.cpp \
           ../xformscommon.cpp \
           ../xmlbuilder.cpp \
           ../prefs.cpp \
           ../section.cpp \
           ../dispatcher.cpp

QT += xml

LIBS += -L../../kxml_compiler -lkschema
LIBS += -L../../schema -lschema
LIBS += -L../../common -lkxmlcommon
LIBS += -L../../compat -lcompat

DUMMY_MOCS = kxformstest.moc formgui.moc guihandlerdialogs.moc guihandlerflat.moc \
  input.moc list.moc mainwindow.moc remotefile.moc formgui.moc dispatcher.moc \
  guielement.moc

system( touch $$DUMMY_MOCS )
